name: Java CI with Maven and MongoDB Atlas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Clean workspace
      - name: Clean workspace
        run: rm -rf target/

      # Step 4: Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 5: Install Maven dependencies (skip tests to save time during install)
      - name: Install dependencies
        run: mvn install -DskipTests

      # Step 6: Run tests (relying on Maven's surefire exclusion rules)
      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: mvn test

      # Step 7: Package the application
      - name: Package application
        run: mvn package -DskipTests -X

      # Step 8: Upload the build artifact (optional)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: employee-jar
          path: target/*.jar
